### ISSUE TITLE
Cryptomagic Repository not found.

### ISSUE THREAD

**Issue by Demontf** [KMSChain/kmschain-sdk-go#1]
In builder.sh
Can not clone and build C++ library
git clone https://github.com/kmschain/cryptomagic.git

**Comment by geghamjivanyan** [comment]
Hi Demontf. 
Thanks for mentioning. Already fixed. Please try again.

**Comment by Demontf** [comment]
Thanks for your help.
I meet another problem when I run "go generate github.com/kmschain/kmschain-sdk-go/kmschain"

msg:
/usr/bin/ld: cannot find -lgtest
/usr/bin/ld: cannot find -lgtest_main
collect2: error: ld returned 1 exit status
CMakeFiles/big_number_test.dir/build.make:121: recipe for target 'big_number_test' failed
make[2]: *** [big_number_test] Error 1
CMakeFiles/Makefile2:181: recipe for target 'CMakeFiles/big_number_test.dir/all' failed
make[1]: *** [CMakeFiles/big_number_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Linking CXX executable re_encryption_test
[100%] Linking CXX executable c_interface_test
/usr/bin/ld: cannot find -lgtest
/usr/bin/ld: cannot find -lgtest_main
collect2: error: ld returned 1 exit status
CMakeFiles/re_encryption_test.dir/build.make:121: recipe for target 're_encryption_test' failed
make[2]: *** [re_encryption_test] Error 1
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/re_encryption_test.dir/all' failed
make[1]: *** [CMakeFiles/re_encryption_test.dir/all] Error 2
/usr/bin/ld: cannot find -lgtest
/usr/bin/ld: cannot find -lgtest_main
collect2: error: ld returned 1 exit status
CMakeFiles/c_interface_test.dir/build.make:121: recipe for target 'c_interface_test' failed
make[2]: *** [c_interface_test] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/c_interface_test.dir/all' failed
make[1]: *** [CMakeFiles/c_interface_test.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
cp: cannot stat 'libcryptomagic.a': No such file or directory
